version: "3.9"
services:
  coingase-feed:
    build: 
      context: .
      dockerfile: .docker-compose/Dockerfile-coninbase-feed
    image: coinbase-feed
    depends_on: 
      - rabbitmq
    environment:
      - NODE_ENV=docker

  crypto-ticker-listener:
    build: 
      context: .
      dockerfile: .docker-compose/Dockerfile-crypto-ticker-listener
    image: crypto-ticker-listener
    depends_on: 
      - rabbitmq
    environment:
      - NODE_ENV=docker
    deploy:
      mode: replicated
      replicas: 3

  web-interface:
    build: 
      context: .
      dockerfile: .docker-compose/Dockerfile-webapp
    image: web-interface
    ports:
      - 8080:80
  
# Infrastructure
# Rabbit MQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./.docker-compose/.data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-compose/.data/rabbitmq/logs/:/var/log/rabbitmq/
    