FROM php:8.2-cli-alpine3.17


RUN apk add g++
RUN apk add autoconf
RUN apk add make
RUN apk add librdkafka-dev

RUN pecl install rdkafka
RUN echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/rdkafka.ini

RUN apk add --no-cache bash
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash
RUN apk add symfony-cli

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

WORKDIR /app/message-listener-php
COPY message-listener-php .
COPY .env/.env.docker .env.prod
RUN composer install
RUN php bin/console cache:clear -e prod

CMD [ "php", "bin/console", "app:start-websocket", "-vvv", "-e", "prod" ]